//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeCalculatorService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/AdditionOperation", ReplyAction="http://tempuri.org/ICalculatorService/AdditionOperationResponse")]
        double AdditionOperation(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/AdditionOperation", ReplyAction="http://tempuri.org/ICalculatorService/AdditionOperationResponse")]
        System.Threading.Tasks.Task<double> AdditionOperationAsync(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/SubractionOperation", ReplyAction="http://tempuri.org/ICalculatorService/SubractionOperationResponse")]
        double SubractionOperation(double number1, double number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/SubractionOperation", ReplyAction="http://tempuri.org/ICalculatorService/SubractionOperationResponse")]
        System.Threading.Tasks.Task<double> SubractionOperationAsync(double number1, double number2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : ConsumeCalculatorService.ServiceReference1.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<ConsumeCalculatorService.ServiceReference1.ICalculatorService>, ConsumeCalculatorService.ServiceReference1.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AdditionOperation(double number1, double number2) {
            return base.Channel.AdditionOperation(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> AdditionOperationAsync(double number1, double number2) {
            return base.Channel.AdditionOperationAsync(number1, number2);
        }
        
        public double SubractionOperation(double number1, double number2) {
            return base.Channel.SubractionOperation(number1, number2);
        }
        
        public System.Threading.Tasks.Task<double> SubractionOperationAsync(double number1, double number2) {
            return base.Channel.SubractionOperationAsync(number1, number2);
        }
    }
}
